name: Deploy TXT file to IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Copy TXT file to IIS
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy TXT file to IIS folder
        run: |
          powershell.exe -ExecutionPolicy Bypass -Command "Copy-Item -Path '.\Deplo.txt' -Destination 'C:\inetpub\wwwroot\TestSite\Deplo.txt' -Force"
